# Generated by Django 5.1.2 on 2024-10-14 08:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog_app", "0003_category_slug_alter_category_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
    ]
